<?php 
//echo "<pre>";print_r( $this->academicresult);die;
?>
<style type="text/css">
    .dd_faculty_list{
        padding-top: 10px;
        font-weight: bold;
    }
    .select2-container{
	z-index: 999;
}
</style>    
<div style="overflow-x:scroll">
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead >
					<tr >
						
						
						<th style="width:10%;">Course Category Name</th>
						<th style="text-align:center;width:14%;">Course Name </th>
						
						<th style="width:5%;">Credit Value </th>
					<!--	<th>Department </th>  -->
						<th style="text-align:center;width:22%;">Course Coordinator</th>
						<th style="text-align:center;width:22%;">Faculty</th>
                                                <th style="text-align:center; width:14%;">Visiting Faculty<br/>(Practitioner/Academic)</th>
						<th style="text-align:center;">Remarks</th>

					</tr>
				</thead>
				
			
				<tbody>
									<?php if(!empty($this->item_result)){
									$i = 1;
                                                                        $disable_co_faculty = false;
                                                                        $isfaculty = false;
									foreach($this->employee_result as $key=>$val){ 
                                                                            $EmployeeAllotment_model = new Application_Model_EmployeeAllotment();
						   $existed_result = $EmployeeAllotment_model->getExistedFaculty($val['academic_year_id'],$val['term_id'],$val['cc_id'],$val['course_id']); 
                                                   //print_r($existed_result);
                                                   
                                                   //If faculty is logged in and the faculty doesn't belong to administrator role set, don't show the row
                                                   if($existed_result['employee_id'] != $this->login_empl_id && !in_array($this->role_id,$this->administrator_role)){
                                                       if($existed_result['faculty_id'] == $this->login_empl_id){//If current user is faculty
                                                           $isfaculty = TRUE;
                                                       }
                                                       else{
                                                           continue;
                                                       }                                                       
                                                   }
                                                   //If role id doesn't below to adminstrator role
                                                   if(!in_array($this->role_id,$this->administrator_role)){
                                                       $disable_co_faculty = true;
                                                   }
										?>
										<tr>
                                <input type="hidden" name="ead_id[]" value="<?php echo $existed_result['ead_id']; ?>"/>
											
											<input type="hidden" name="employee[term_id][]" id="term_id<?php echo $i;?>" value="<?php echo $val['term_id']; ?>" />
											<td><?php echo $val['cc_name'];?></td>
											<input type="hidden" name="employee[cc_id][]" id="cc_id<?php echo $i;?>" value="<?php echo $val['cc_id']; ?>" /> 											
											<td><?php echo $val['course_name'];?></td>
											<input type="hidden" name="employee[course_id][]" id="course_id<?php echo $i;?>" value="<?php echo $val['course_id']; ?>" /> 
											<td><?php echo $val['credit_value'];?></td> 
											<input type="hidden" name="employee[credit_id][]" id="credit_id" value="<?php echo $val['credit_id']; ?>" />
				<!--		<td><select id="department_name<?php echo $i;?>" name="employee[department_id][]" class="form-control" onchange="select_department(this.value,<?php // echo $i;?>)">
						   <?php /* foreach($this->department as $d=>$dept){
							   $selected = '';
									if($d == $val['department_id']) { 
										$selected = "selected";
										} */
									?>
						   <option value="<?php // echo $d;?>" <?php // echo $selected;?>><?php // echo $dept;?></option>
						   <?php // } ?>
						   </select></td>  -->
						   <?php 
                                                   //print_r($existed_result);
                                                   ?>
<input type="hidden" id="department_name<?php echo $i;?>" name="employee[department_id][]" value='1'>
                                                                                        <td><select data-si-no="<?php echo $i;?>" id="employee_name<?php echo $i;?>" name="employee[employee_id][]" class="form-control faculty_list_dd" <?php if($disable_co_faculty){echo 'disabled = "disabled"';} ?>>
											<option value="">Select</option>
						   <?php foreach($this->employee as $e=>$emp){
									$selected = '';
									if($e == $existed_result['employee_id']){
										$selected = "selected";
									}?>
						   <option value="<?php echo $e;?>" <?php echo $selected; ?>><?php echo $emp;?></option>
						   <?php } 
                                                   $faculty_ids = explode(',', $existed_result['faculty_id']);
                                                   ?>
						   </select>
                                                                                        
                                                                                        <input type="hidden" id="default-emp<?php echo $i;?>" value="<?php echo $existed_result['employee_id']; ?>" />
                                                                                        </td>
                                                                                        <td>
                                                                                            <?php
                                                        $selected_faculty = array();
                                                        ?>
                                                                                            <select multiple="multiple" id="faculty_name<?php echo $i;?>" name="employee[faculty_id][<?php echo $val['course_id']; ?>][]" class="form-control f-list"  <?php if($isfaculty){echo 'disabled = "disabled"';} ?>>
											<option value="">Select</option>
                                                                                        <option value="NA" <?php if(in_array('NA',$faculty_ids)){echo 'selected="selected"';$selected_faculty[] = 'N/A';} ?>>N/A</option>
						   <?php                                                   
                                                   foreach($this->employee as $em=>$empe){
									$selected = '';
                                                                        
									if(in_array($em, $faculty_ids)){
										$selected = "selected";
                                                                                $selected_faculty[] = $empe;
									}?>
						   <option value="<?php echo $em;?>" <?php echo $selected; ?>><?php echo $empe;?></option>
						   <?php } 
                                                   $visiting_ids = explode(',', $existed_result['visiting_faculty_id']);
                                                   ?>
						   </select>
                                                                                            
                                                                                        </td>
						    <td>
                                                        <?php
                                                        $selected_faculty = array();
                                                        ?>
                                                        <select multiple="multiple" id="visiting_faculty_name<?php echo $i;?>" name="employee[visiting_faculty_id][<?php echo $val['course_id']; ?>][]" class="form-control vf-list" <?php if($isfaculty){echo 'disabled = "disabled"';} ?>>
											<option value="">Select</option>
                                                                                        
                                                                                        <option value="NA" <?php if(in_array('NA',$visiting_ids)){echo 'selected="selected"';$selected_faculty[] = 'N/A';} ?>>N/A</option>
						   <?php                                                   
                                                   foreach($this->visitingemployees as $vem=>$vempe){
									$selected = '';
									if(in_array($vem, $visiting_ids)){
										$selected = "selected";
                                                                                $selected_faculty[] = $vempe;
									}?>
						   <option value="<?php echo $vem;?>" <?php echo $selected; ?>><?php echo $vempe;?></option>
						   <?php } ?>
						   </select>
                                                        
                                                    </td>
						   <td ><textarea style="height:35px !important;width:220px !important;" name="employee[remarks][]" id="remarks<?php echo $i;?>" class="form-control"><?php echo $existed_result['remarks'];?></textarea></td>

										
		                               </tr>
									   
									  
									   <?php
                                                                           $isfaculty = FALSE;
									  $disable_co_faculty = false;
											$i++; 
											}
									
									}
									
										else{
											$i = 1;
											
										?>
										
										<?php if(!empty($this->employee_result)){
										foreach($this->employee_result as $key=>$val){ 
										?>
										<tr>
										
											
											
											<input type="hidden" name="employee[term_id][]" id="term_id" value="<?php echo $val['term_id']; ?>" />
											<td><?php echo $val['cc_name'];?></td>
											<input type="hidden" name="employee[cc_id][]" id="cc_id" value="<?php echo $val['cc_id']; ?>" /> 											
											<td><?php echo $val['course_name'];?></td>
											<input type="hidden" name="employee[course_id][]" id="course_id" value="<?php echo $val['course_id']; ?>" /> 
											<td><?php echo $val['credit_value'];?></td> 
											<input type="hidden" name="employee[credit_id][]" id="credit_id" value="<?php echo $val['credit_id']; ?>" />
				<!-- 		<td><select id="department_name<?php // echo $i;?>" name="employee[department_id][]" class="form-control" onchange="select_department(this.value,<?php // echo $i;?>)">
						   <?php /* foreach($this->department as $k=>$val){ ?>
						   <option value="<?php echo $k;?>"><?php echo $val;?></option>
						   <?php } */ ?>
						   </select></td>  -->
<input type="hidden" id="department_name<?php echo $i;?>" name="employee[department_id][]" value='1'>
											<td><select id="employee_name<?php echo $i;?>" name="employee[employee_id][]" class="form-control">
						   <?php foreach($this->employee as $k=>$val1){ ?>
						   <option value="<?php echo $k;?>"><?php echo $val1;?></option>
						   <?php } ?>
						   </select></td>
						   <td><select multiple="multiple" id="faculty_name<?php echo $i;?>" name="employee[faculty_id][<?php echo $val['course_id']; ?>][]" class="form-control f-list">
                                                           <option value="NA">N/A</option>
						   <?php foreach($this->employee as $k=>$val1){ ?>
						   <option value="<?php echo $k;?>"><?php echo $val1;?></option>
						   <?php } ?>
						   </select>                                                   
                                                   </td>
                                                   <td><select multiple="multiple" id="visiting_faculty_name<?php echo $i;?>" name="employee[visiting_faculty_id][<?php echo $val['course_id']; ?>][]" class="form-control vf-list">
                                                           <option value="NA">N/A</option>
						   <?php foreach($this->visitingemployees as $k=>$val){ ?>
						   <option value="<?php echo $k;?>"><?php echo $val;?></option>
						   <?php } ?>
						   </select>
                                                   </td>
						   <td><textarea name="employee[remarks][]" id="remarks<?php echo $i;?>"></textarea></td>
		                               </tr>
									   <?php 
											$i++; }
											}
											}
											?>
								
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
</div>	
		
<script>
$('#formValidate1').submit(function() {
      $('select').attr('disabled',false);
});
function select_department(value,num){
	var department_name = value;
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-department-name';?>',
			data: {department_name:department_name}
			
		}).done(function( data ) {
			
				
			$('#employee_name'+num+'').empty('');
			$('#employee_name'+num+'').append(data);
			
		
			
		 });
}
		/*$("#department_name").change(function(){
	
	
	var department_name=$('#department_name').val();
	//alert(department_name);
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-department-name';?>',
			data: {department_name:department_name}
			
		}).done(function( data ) {
			
				
			$('#employee_name').empty('');
			$('#employee_name').append(data);
			
		
			
		 });
}); */
    
    $('.faculty_list_dd').change(function(){
        //saving the default value        
        var si_no = $(this).data('si-no');
        var batch_id = $('#academic_year_id').val();
        var term_id = $('#term_id'+si_no).val();
        var course_id = $('#course_id'+si_no).val();
        var faculty_id = $('#default-emp'+si_no).val();
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'master/ajax-is-grade-allocated';?>',
                data: {batch_id:batch_id,term_id: term_id, course_id: course_id, faculty_id: faculty_id}

        }).done(function( data ) {
                if(data == 1){
                    $('#employee_name'+si_no).val(faculty_id);
                    alert("Grade is already generated. First, delete the grade before editing it.")
                }
                    
         });
    });
    $(document).ready(function(){
    /*
        $("select.vf-list, select.f-list").change(function(){
            //var el = $(e+" option:selected");
            var op_list = $( this ).find("option:selected");
            var str = "";
            $( op_list ).each(function() {                
               str += $( this ).text() + "<br/>";
            });
            $( this ).next('div').html( str );
            //var selectedCountry = $(".vf-list option:selected").val();
            //alert("You have selected the country - " + selectedCountry);
        });
        */
        $('select.vf-list, select.f-list').select2();
    });
</script>