<style>

    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }

    dt{
        display:none;
    }

    table.table-bordered.dataTable tbody td {      
        padding: 0 ;
        margin-bottom: 0px ;
        vertical-align: middle ;
    }


</style>
<link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet">
<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md">
            <div class="row">
                <div class="col-md-12 " >
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Exam Fee</i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

                                   


                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label  class="control-label" >Batch<span class="asterisk">*</span></label>
                                            <?php echo $this->form->batch; ?>
                                            <input type='hidden' value ='' name='acad_id' id ='acad_id' />
                                        </div>
                                    </div>
                                    
                                        <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Term<span class="asterisk">*</span></label>
                                            <?php echo $this->form->term; ?>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                   
                                        
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">List of Papers<span class="asterisk"></span></label>
                                            <select class="form-control" multiple="multiple" name="courseBox[]" id="course_id"></select>
                                            <div class="course_selected_div"></div>

                                            <input type="hidden" id="hdn_course_ids" value="" />
                                        </div>
                                    </div>
                                    

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Fee<span class="asterisk">*</span></label>
                                            <?php echo $this->form->fee; ?>
                                        </div>
                                    </div>
                                  

                                </div>
                                <div class="row">
                                  <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Paper<span class="asterisk">*</span></label>
                                            <?php echo $this->form->paper; ?>
                                        </div>
                                    </div>      
                                </div>
                            </div>

                    </div>
                    <div class="row">

                    </div>
                    </div> 







                    <!--	 <?php /* if(count($this->item_result)>0){
                                          //		print_r($this->item_result);die;
                                          $i=0;
                                          foreach($this->item_result as $val){
                                          $i++; */
                                            ?>
                    <div class="row" id="" style="">
                    
                                    <div class="col-sm-3">
                                    <label>Fee Head Name<span class="asterisk">*</span></label>
                                    <input type="text"  label="feehead_name_<?php // echo $i;                  ?>"  class="form-control feehead_name" name="Fee[feehead_name][]" placeholder="" value="<?php echo $val['feehead_name']; ?>"/> 
                                    </div>				  
                                                                                    
                            <a href="#" class="removeclass btn btn-primary remove_class" style="padding:7px 15px;margin:24px 15px; ">-</a>
                            </div>   
                    <?php // } ?>
                     <div class="col-sm-3"></div>    
                    <input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin-left:9px;">
                    
                    <?php // }  else {    ?>
                     
        <input type="hidden" name="count_val" id="count_val" value="1" class="count_val" />  
        <div class="row" style="">

        <div class="col-sm-3"><label> Fee Head Name <span class="asterisk">*</span></label> <input type="text"  label="feehead_name_0"  class="form-control" name="Fee[feehead_name][]" style="" placeholder="Name" value="" /> 
        </div>
        <input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin:24px 15px;"> 


        </div>
                    <?php // } ?>
        <div id="fields">
        <div class="padding-top"></div>
        </div>   -->
                </div>
                <div>
                    <div class="panel-footer">									
                        <div class="row">
                            <div class="col-sm-7 col-sm-offset-5">
                                <?php if ($this->type == 'add') { ?> 
                                    <div style="float:left;margin-right:2px;">
                                        <button class="btn btn-primary submit">Submit</button>
                                    </div>
                                    <div style="float:left;padding:0px 10px;">
                                        <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                    </div>
                                <?php } else { ?>
                                    <div style="float:left;">
                                        <button class="btn btn-primary submit">Update</button>
                                    </div>
                                    <div style="float:left;">
                                        <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/coursefee/">Back</a>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
                </form>
            </div><!-- /panel -->
        </div><!-- /.col-->				
    </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <?php echo $this->escape($message); ?>
            </div>
            <?php
        }
    }
    ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Exam Fee List </i>

                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/coursefee/type/add">Add </a>
                </div>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <h2>Exam Fee List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
              
                    <div class="x_content">
                       

                                <div >
                                    <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                                        <thead>
                                            <tr>
                                                <th style="text-align:center;">S.No.</th>	
                                                <th style="text-align:center;">Batch</th>
                                                <th style="text-align:center;">Term</th>
                                                <th style="text-align:center">Paper</th>
                                                <th style="text-align:center;">Fee</th>
                                                <th style="text-align:center;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody style="text-align:center;">
                                  <?php           if (count($this->paginator) != 0) {

                            $j = 1;
                            foreach ($this->subtable as $key => $value) {
                              
                                $i = 1;
                                ?>


                                                    <tr>
                                                        <td><?php
                                                            echo $j;
                                                            $i++;
                                                            ?>
                                                        </td>						


                                                        <td><?php echo $value['batch']; ?></td>

                                                        <td><?php echo $value['term']; ?></td>
                                                        <td><?=$value['paper']==1?'Current Paper':'Back paper';?></td>
                                                        <td><?php echo $value['fee']; ?></td>
                                                        <td><a href="<?php echo $this->mainconfig['host']; ?>master/coursefee/type/edit/id/<?php echo $value['id']; ?>" class="edit" title="Edit">Edit</a>&nbsp;</td>

                                                    </tr>    
                                          

                                                    
                                                         <?php
                                $j++;
                            }
                            ?>
                        <?php } ?> 
                                                    
                                        </tbody>
                                    </table>
                                </div>

                                              </div>
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script>    
<script>

  
    $('#due_date').attr('autocomplete', 'off');
    $(function () {
        $('#due_date').datetimepicker();
    });



    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }


    $("#batch").change(function () {
        var academic_id = $('#batch').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term').empty('');
                $('#term').html(data);
                //$('#term_b_id').empty('');
                //$('#term_b_id').html(data);
            })
        }
    });



    $("#term").change(function () {
        var term_id = $('#term').val();
        var academic_id = $('#batch').val();
        // alert(academic_id);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'attendance/ajax-get-course'; ?>',
            data: {academic_year_id: academic_id, term_id: term_id}
        }).done(function (data) {

            $('#course_id').empty('');
            $('#course_id').html(data);

            $('#course_id option').prop('selected', true);
            $('#course_id option:nth-child(1)').prop('selected', false);

        })

    });



    $("#term_b_id").change(function () {
        var term_id = $('#term_b_id').val();
        var academic_id = $('#academic_year_id').val();
        // alert(academic_id);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'attendance/ajax-get-course'; ?>',
            data: {academic_year_id: academic_id, term_id: term_id}
        }).done(function (data) {
            //alert(data);



            $('#course_b_id').empty('');
            $('#course_b_id').html(data);




            $('#course_b_id option').prop('selected', true);
            $('#course_b_id option:nth-child(1)').prop('selected', false);

        });

    });




    $("#date").change(function () {
        var term_id = $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
        var date_val = $("#date").val();
        var id = $(this).attr("id");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'attendance/ajax-student-list-view'; ?>",
            data: {batch_id: academic_id,
                term_id: term_id, course_id: course_id, date_val: date_val}
        }).done(function (data) {
            $('#item_details').empty('');
            $("#item_details").html(data);
        });
    });



    $('body').on('change', '#batch', function () {
        var academic_id = $('#batch').val();
        if (academic_id) {
             $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                    data: {academic_year_id: academic_id}
                }).done(function (data) {
                    $('#term').empty();
                    $('#term').html(data);
                    
                    });
        }
    });


    var academic_id = $('#batch option:selected').val();
    if (academic_id) {


        $('#batch').val(academic_id);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {
            var result = $.parseJSON(data);
            if ((data != '')) {
                //$('#batch').val(result['short_code']);
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                    data: {academic_year_id: academic_id}
                }).done(function (data) {
                    //alert(data);
                    $('#term').empty('');
                    $('#term').html(data);
                    $('#term').val("<?php echo $_SESSION['application']['term_id']; ?>");
           



                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'attendance/ajax-get-course'; ?>',
                        data: {academic_year_id: academic_id, term_id: $('#term').val()}
                    }).done(function (data) {
                        //alert(data);



                        $('#course_id').empty('');
                        $('#course_id').html(data);
                        var course_id = '<?php echo $_SESSION['application']['course_id']; ?>';

                        //  $('#course_id option').prop('selected', true);

                        course_id = course_id.split(",");
                        for (x in course_id) {

                            $("#course_id option[value='" + course_id[x] + "']").attr('selected', true);
                        }

                        $('#course_id option:nth-child(1)').prop('selected', false);

                    });

                })
            }
        });
    } else {
       // $('#batch').hide();
    }


    $('#dataTable').DataTable();
    function onStudentSelect() {
        var op_list = $('#course_id').find("option:selected");
        var str = "";
        $(op_list).each(function () {
            str += $(this).text() + "<br/>";
        });
        $('#course_id').next('div').html(str);
    }
    function onStudentSelect2() {
        var op_list = $('#course_id_b').find("option:selected");
        var str = "";
        $(op_list).each(function () {
            str += $(this).text() + "<br/>";
        });
        $('#course_b_id').next('div').html(str);
    }
    $(document).ready(function () {
        $("#course_id").change(function () {

            onStudentSelect2()
        });
        $("#course_id").change(function () {

            onStudentSelect2()
        });
        $('#dob').attr('autocomplete', 'off');

        $("#dob").datepicker({dateFormat: 'dd/mm/yy'});
    });

    $('#course_id').select2();
</script>
