
<style type="text/css">
    
    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }
    
</style>

<style>
    
    
 
    
    @media print {
                    table td:nth-child(9)
                     {
                         display:none;
                     }
                     table th:nth-child(9)
                     {
                         display:none;
                     }
                     table td:nth-child(10)
                     {
                         display:none;
                     }
                     table th:nth-child(10)
                     {
                         display:none;
                     }
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                }
                
                
                
                #custom_data_records{
                    width:100%;
                    text-align: right;
                    font-size:1.5em;
                    
                }
                
      
      
</style>
<div class="right_col">

<?php if ($this->type) { ?>
<div class="padding-md">
    <?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div <?php if($_SESSION['admin_login']['admin_login']->flash_error==0){echo 'class="alert alert-danger"';$_SESSION['admin_login']['admin_login']->flash_error=1;}else{ echo "class='alert alert-success'"; } ?>>
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Participants Enrollment</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley"  enctype="multipart/form-data">
					
					<div class="panel-body">
					
					<div class="row">
					<div class="col-sm-3"><h4><span style="color:#777;">Academic Details</span></h4></div>
					</div>
					 <div class="row masterbox">
					 <div class="row">
					      <div class="col-sm-3 employee_class">
                            <div class="form-group disabled" >
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_id; ?>
                            </div>
							</div>
							
							<!--<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Term<span class="asterisk">*</span></label>
                                <?php //echo $this->form->terms_id; ?>
                            </div>
							</div> 
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year; ?>
                            </div>
							</div>-->
				<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Participant ID<span class="asterisk">*</span></label>
                              <div style="position:absolute">
                                <?php echo $this->form->stu_id; ?>
                              </div>
                             <!-- <div style="position:absolute"><input id='read_id' class="form-control" type='text' readonly="" value=""/></div>-->
                            </div>
							</div>
                                                       
                                                        <?php if($this->type=='edit'): ?>
                                                        <div class="col-sm-offset-3 col-sm-3 employee_class">
                                                            <div class="form-group">
                                                                <?php if($this->result['filename']): ?>
                                                                <img class="img img-rounded" src="<?=$this->baseUrl($this->result['filename']);?>" width="100px" alt="img" />
                                                                <?php endif; ?>
                                                            </div>
							</div>
                                                        <?php endif; ?>
                                                        
                                                        
                                                        <?php 
                                                        if ($this->type == 'add'){
                                                        ?>
                                                        <div class="col-sm-3 employee_class">
                                    <div class="form-group disabled">
                                        <label class="control-label">&nbsp;</label><br/>
                         <button id="btn-get-discont-student" class="block" onclick="fetchDiscontinuedStudentDetail();return false;">Get Discontinued Participant Detail</button>
                                            </div>
							</div>
                                                        <?php
                                                        }
                                                        ?>
                                                        
.							
					 </div>
					 <div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;" readonly /></div>
							</div>
                                    </div>
					 </div>
					
					<div class="row">
							
					<div class="col-sm-3"><h4><span style="color:#777;">Participants Details</span></h4></div>
					</div>
						<div class="row masterbox">
					     <div class="row">	
						
						   <div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">First Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->stu_fname; ?>
                            </div>
							</div> 
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Last Name<span class="asterisk">*</span></label>
                                <?php echo $this->form->stu_lname; ?>
                            </div>
							</div>

                            <div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Gender<span class="asterisk">*</span></label>
                                <?php echo $this->form->gender; ?>
                            </div>
							</div>	

							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Mobile Number<span class="asterisk">*</span></label>
                                <?php echo $this->form->stu_mobileno; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Email ID<span class="asterisk">*</span></label>
                                <?php echo $this->form->stu_email_id; ?>
								<span id="erremail" style="color:red;"></span>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Date of Birth</label>
                                <?php echo $this->form->stu_dob; ?>
                            </div>
							</div>
                                                 
                                                 <div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Blood Group</label>
                                <?php echo $this->form->blood_group; ?>
								<span id="erremail" style="color:red;"></span>
                            </div>
							</div>
															
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Present Address<span class="asterisk">*</span></label>
                                <?php echo $this->form->present_addr; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Permanent Address</label>
                                <?php echo $this->form->premanent_addr; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                                <label class="control-label">Status &nbsp;&nbsp;<?php if($this->result['participant_Alumni']==1) { ?>  <span id='Alumni_text' style="color:red;">(Alumni)</span><?php } ?></label>
                                <?php echo $this->form->stu_status; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label" id="eff_date">Effective Date</label>
                                <?php echo $this->form->effective_date; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label" id="advice_label">Advice</label>
                                <?php echo $this->form->adv_col; ?>
                            </div>
							</div>
							
						</div>	
				     </div>	
					<div class="row">	
					<div class="col-sm-3"><h4><span style="color:#777;">Parent Details</span></h4></div>
					</div>
					     
							<div class="row masterbox">
							 <div class="row">
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Father First Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->father_fname; ?>
                            </div>
							</div> 
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Father Last Name<span class="asterisk">*</span></label>
                                <?php echo $this->form->father_lname; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Father Mobile Number<span class="asterisk">*</span></label>
                                <?php echo $this->form->father_mobileno; ?>
                            </div>
							</div>
							
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Mother First Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->mother_fname; ?>
                            </div>
							</div>
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Mother Last Name<span class="asterisk">*</span></label>
                                <?php echo $this->form->mother_lname; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Mother Mobile Number</label>
                                <?php echo $this->form->mother_mobileno; ?>
                            </div>
							</div>
                                                             
                                                             <div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Linkedin URL</label>
                                <?php echo $this->form->linked_in; ?>
                              <span id="erremail2" style="color:red;"></span>
                            </div>
							</div>
							
						 </div>
                                                               <div class="col-sm-3 employee_class">
                            <div class="form-group disabled">
                              <label class="control-label">Secondary Email</label>
                                <?php echo $this->form->secondary_mail; ?>
                              <span id="erremail1" style="color:red;"></span>
                            </div>
							</div>
							
						 </div>
						</div>
                                            
                                            <div class="row alumni_panel">	
					<div class="col-sm-3"><h4><span style="color:#777;">Year of Passing & Alumni Entry</span></h4></div>
                                        </div>
                                        <div class="row masterbox alumni_panel">
							 <div class="row">
							 <div class="col-sm-3 employee_class">
							  <?=$this->form->passing_year;?>
                                                             <h5 id="nexterror"></h5>
							 </div>
                                                             <div class="col-sm-3">
                                                                
                                                                 <input type="checkbox" style="zoom:2" value="1" <?php if($this->result['participant_Alumni']==1)
                                                                     {echo 'checked'." ";echo 'onclick ="return ConfirmDelete(&quot;Are you sure you want delete this participant as Alumni ?&quot;);"' ;}else{echo 'onclick ="return ConfirmDelete(&quot;Are you sure you want make this participant as Alumni ?&quot;);"';}?> id="passing_status" name="passing_status"  />&nbsp;<span class="bold-checkbox"> Check To Create Alumni !</span>
                                                             </div>
                                                             <div class="col-sm-3">
                                                                
                                                                 <input type="checkbox" style="zoom:2" value="1" <?php if($this->alumni_detail['display_phone']==1)
                                                                 {echo 'checked'." ";}?> id="display_phone" name="display_phone"  />&nbsp;<span class="bold-checkbox">Publish Phone Number</span>
                                                             </div>
							 </div>
					</div>	
                                             <div id="participants_credentials" >
					<div class="row">	
					<div class="col-sm-3"><h4><span style="color:#777;">Enter participants Credentials</span></h4></div>
                                        </div>
                                     <div class="row masterbox">
							 <div class="row">
                                                                	<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">User Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->participant_username; ?>
                            </div>
							</div>
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Password<span class="asterisk">*</span></label>
                                <?php echo $this->form->participant_pword; ?>
                              <div class="form-control-static">
                                    Default Password - 6 digit mobile number(XXXX123456)
                              </div>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label" >Confirm Password<span class="asterisk">*</span></label>
                                <?php echo $this->form->confirm_password; ?><br/>
                              <h5 id="error"></h5>
                            </div>
							</div>
                                                             
                                                             
                                                               <div class="col-sm-3">
                                                                 
                                                                   <span class="glyphicon glyphicon-eye-close" style="position: absolute; top: 32px; font-weight:bold; cursor:pointer;" id="show_password"></span>  <label class="control-label" style="display:none" id="password_label">Show Password</label>
							 </div>
					</div>	
                                                                    
                                                             </div>
                                                             </div>
                                                  
                                        </div>
					<div class="row">	
					<div class="col-sm-3"><h4><span style="color:#777;">File Upload</span></h4></div>
					</div>
					<div class="row masterbox">
							 <div class="row">
							 <div class="col-sm-3 employee_class">
                                                             <input name="file[]" id="file" type="file" accept="image/jpg, image/jpeg, image/png"  />
                                                                <div class='form-control-statuc' >
                                                              <span class='text-danger'>*only .jpg or .png files can be upload</span>
                                                          </div>
							 </div>
							 </div>
					</div>		 
						
			</div>
		
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit" onclick="return confirmPword();">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default" >Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit" onclick="return confirmPword();">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>student/index">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
<!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div <?php if($_SESSION['admin_login']['admin_login']->flash_error==0){echo 'class="alert alert-danger"';$_SESSION['admin_login']['admin_login']->flash_error=1;}else{ echo "class='alert alert-success'"; } ?>>
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">Participants Enrollment</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>student/index/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                        <h2 class="title1">Participants Details</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
                    <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.  No.</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Mobile Number</th>
						<th>Email ID</th>
						<th>Father Name</th>
						<th>Batch</th>
						<!-- <th>Year</th>  -->
						<th>Participant ID</th>
						<th></th>
						<!--<th>Term Name</th>-->
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								<td><?php echo $results['stu_fname']; ?></td>
								<td><?php echo $results['stu_lname']; ?></td>
								<td><?php echo $results['stu_mobileno']; ?></td>
								<td><?php echo $results['stu_email_id']; ?></td>
								<td><?php echo $results['father_fname']; ?></td>
								<td><?php echo $results['academic_year']; ?></td>
								
								<!-- <td><?php /*if($results['year']==1){
									echo'First Year';
								}
								else{
									echo'Second Year';
								}
								 */?></td> -->
								<td><?php echo $results['stu_id']; ?></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>student/index/type/download/file/<?php echo $results['filename']; ?>/id/<?php echo$results['student_id'];?>"> Download </a></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>student/index/type/edit/id/<?php echo $results['student_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>student/index/type/delete/id/<?php echo $results['student_id']; ?>" onclick="return ConfirmDelete('Are you sure you want to delete this ?');" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>
							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>

<script>
    
    $('#stu_status').change(function(){
        var  x = $(this).val();
        if(x=='2'){
            $('.alumni_panel').hide();
        }
        else
        {
             $('.alumni_panel').show(); 
        }
    });
    
    $('#stu_email_id').blur(function(){
     var n = $("#stu_email_id").val().indexOf("@");
    var res = $('#stu_email_id').val().substr(0, n);
    var mobile_len = $('#stu_mobileno').val().length;
     var default_pword = $('#stu_mobileno').val().substr(mobile_len-6,mobile_len); 
      $('#participant_username').val(res);
      $('#participant_pword').val(default_pword);
         $('#confirm_password').val(default_pword);
    });
    $('#stu_mobileno').blur(function(){
         var n = $("#stu_email_id").val().indexOf("@");
    var res = $('#stu_email_id').val().substr(0, n);
    var mobile_len = $('#stu_mobileno').val().length;
     var default_pword = $('#stu_mobileno').val().substr(mobile_len-6,mobile_len);
      $('#participant_username').val(res);
      $('#participant_pword').val(default_pword);
         $('#confirm_password').val(default_pword);
    });
    
     $("#show_password").click(function (){ 
       if($("#show_password").attr("class")=="glyphicon glyphicon-eye-close"){
           $("#show_password").attr("class","glyphicon glyphicon-eye-open");
           $("#password_label").empty();
            $("#password_label").text("Hide Password");
       $('#participant_pword').attr('type','text');
   $('#confirm_password').attr('type','text');}
       else{
           $("#show_password").attr("class","glyphicon glyphicon-eye-close");
           $('#participant_pword').attr('type','password');
            $('#confirm_password').attr('type','password');
             $("#password_label").empty();
            $("#password_label").text("Show Password");
       }}); 
    
$(document).ready(function() {	
    if ($('#passing_status').is(':checked'))
        $('#passing_year').attr("required","required");
    
    if($("#stu_email_id").val() || $('#stu_mobileno').val()){
    var n = $("#stu_email_id").val().indexOf("@");
    var res = $('#stu_email_id').val().substr(0, n);
    var mobile_len = $('#stu_mobileno').val().length;
     var default_pword = $('#stu_mobileno').val().substr(mobile_len-6,mobile_len);
 }
     if($('#participant_username').val()=='')
     {
     $('#participant_username').attr("required","required");
     $('#participant_username').val(res);
     
     $('#participant_pword').attr("required","required");
     $('#participant_pword').val(default_pword);
     $('#confirm_password').attr("required","required");
     $('#confirm_password').val(default_pword);
                                      }
                                      else
                                      {
                           $('#participant_username').removeAttr("required");
                           $('#participant_pword').removeAttr("required");
                            $('#confirm_password').removeAttr("required");
                                          }
	//$("#stu_dob").datepicker({ dateFormat: 'dd-mm-yy' });  
	$('#stu_dob').datepicker( {format: 'dd/mm/yyyy'} );
	$('#effective_date').datepicker( {format: 'dd/mm/yyyy'} );
	
}); 


function confirmPword(){
  
    var password = $("#participant_pword").val();
    var confirm_pword =$("#confirm_password").val(); 
    if(password == confirm_pword)
    {
        
        $("#error").text("redirecting..."); 
        $("#error").css("color","green");
        return true;
    }
    else
    {
        $("#error").text('password does not match'); 
        $("#error").css("color","red");
        return false;
    }
    
}

	function ConfirmDelete($data)
                            {
                               var bool = $('input[type=checkbox]').prop('checked');
                                var x = confirm($data);
                                if (x)
                                {     
                                    if(bool==true)
                                             {
                                             $('.collapse').collapse('show');
                                             $('#passing_year').attr("required","required");                                                
                                         }
                                         else if(bool==false)
                                         {
                                            $('.collapse').collapse('hide'); 
                                            $('#passing_year').removeAttr("required");
                                            $('.disabled input,.disabled select,.disabled textarea,.btn,button').removeAttr('disabled');
                                         }
                                    return true;
                                }                    
                                    else
                                {
                                             
                                    return false;
                                }
                               
                            }
	
	
  $("#stu_mobileno").keyup(function(){
	  
	 var stu_mobileno=$("#stu_mobileno").val();
		
		if(!isNaN(stu_mobileno))
		{
		
			if(stu_mobileno.length <11){
			   return true;
			}
			else{
				alert("Mobile Number Should be less than 10 digits");
				$("#stu_mobileno").val("");
			}
		}
		else{
		    alert("Mobile Number Should be Numeric Only");
			$("#stu_mobileno").val("");
		}
	
  });
  
  
  $("#stu_email_id").keyup(function(){
		var email = $("#stu_email_id").val();

		var isValid = isEmailValid(email);
		if(isValid == false){
			//alert("sdffs");
			$('#erremail').text("Please enter valid email");
			// $('#to_email').focus();
			$('#stu_email_id').text("");
			return false;
		}else{
			$('#erremail').text("");
			return true;
		}
});

  $("#secondary_mail").keyup(function(){
		var email = $("#secondary_mail").val();

		var isValid = isEmailValid(email);
		if(isValid == false){
			//alert("sdffs");
			$('#erremail1').text("Please enter valid email");
			// $('#to_email').focus();
			$('#secondary_mail').text("");
			return false;
		}else{
			$('#erremail1').text("");
			return true;
		}
});


function isEmailValid(email) {
		var EMAIL_REGEXP = new RegExp('^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$', 'i');
		return EMAIL_REGEXP.test(email)
}
  
  
$("#father_mobileno").keyup(function(){
	  
	 var father_mobileno=$("#father_mobileno").val();
		
		if(!isNaN(father_mobileno))
		{
		 
			if(father_mobileno.length <11){
			   return true;
			}
			else{
				alert("Mobile Number Should be less than 10 digits");
				$("#father_mobileno").val("");
			}
		}
		else{
		    alert("Mobile Number Should be Numeric Only");
			$("#father_mobileno").val("");
		}
	
  });
  
 $("#mother_mobileno").keyup(function(){
	  
	 var mother_mobileno=$("#mother_mobileno").val();
		
		if(!isNaN(mother_mobileno))
		{
		 
			if(mother_mobileno.length <11){
			   return true;
			}
			else{
				alert("Mobile Number Should be less than 10 digits");
				$("#mother_mobileno").val("");
			}
		}
		else{
		    alert("Mobile Number Should be Numeric Only");
			$("#mother_mobileno").val("");
		}
	
  });
  


$('body').on('change', '#academic_id', function() {		
var academic_id=$('#academic_id').val();
var academic_text=$('#academic_id option:selected').text();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
          
          
          $.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'student/ajax-get-max-id';?>',
			data: {batch_id:academic_id, short_code:academic_text}
		}).done(function( data ) {
			$('#stu_id').val(data);
                        $('#read_id').val(data);
	  });
          
          
          
	 }
	 
 }); 
 

var academic_id=$('#academic_id option:selected').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	
          
          
	 }
	else{
$('#batch').hide();
} 

$(document).ready(function() {
	$('#effective_date').hide();
	$('#adv_col').hide();
	$('#eff_date').hide();
	$('#advice_label').hide();
	$('body').on('change', '#stu_status', function() {		
	var stu_status=$('#stu_status').val();
	
	   if(stu_status == 2){
		$('#effective_date').show();
		$('#adv_col').show();
		$('#eff_date').show();
		$('#advice_label').show();
		}
		else{
		$('#effective_date').hide();
		$('#adv_col').hide();
		$('#eff_date').hide();
		$('#advice_label').hide();
		}
	 }); 
	 
	   var stu_status=$('#stu_status option:selected').val();
	   if(stu_status == 2){
		$('#effective_date').show();
		$('#adv_col').show();
		$('#eff_date').show();
		$('#advice_label').show();
		}
		else{
		$('#effective_date').hide();
		$('#adv_col').hide();
		$('#eff_date').hide();
		$('#advice_label').hide();
		}
});
//Fetch detail of Discontinue person
function fetchDiscontinuedStudentDetail(){
    var participant_id = $("#stu_id").val();
                $.ajax({ 
                                    type: "POST",
                                    url:'<?php echo $this->mainconfig['host'].'student/fetch-discontinued-student-detail';?>',
                                    data: {participant_id:participant_id}
                            }).done(function( data ) {
                                if(data == 0){
                                    alert('No Previous Detail Found for this student');
                                }
                                else{
                                    var result = $.parseJSON(data);
                                    //{"student_id":"29","stu_fname":"Abhishek","stu_lname":"Kumar","gender":"1","stu_mobileno":"9771865393","stu_email_id":"akabhishek119@gmail.com","stu_dob":"","present_addr":"asfasdfasfdafadf","premanent_addr":"asdfasdfasdfasfdasdf","stu_status":"2","effective_date":"14\/02\/2018","adv_col":"test","father_fname":"asdf","father_lname":"asdf","father_mobileno":"123456789","mother_fname":"asdfasdf","mother_lname":"asdf","mother_mobileno":"12345678","academic_id":"2","terms_id":"0","year":"0","stu_id":"PDM03001","status":"0","filename":""}
                                    $('#stu_fname').val(result['stu_fname']);
                                    $('#stu_lname').val(result['stu_lname']);
                                    $('#gender').val(result['gender']);
                                    $('#stu_mobileno').val(result['stu_mobileno']);
                                    $('#stu_email_id').val(result['stu_email_id']);
                                    $('#stu_dob').val(result['stu_dob']);
                                    $('#present_addr').val(result['present_addr']);
                                    $('#premanent_addr').val(result['premanent_addr']);
                                    //$('#stu_status').val(result['stu_status']);
                                    $('#father_fname').val(result['father_fname']);
                                    $('#father_lname').val(result['father_lname']);
                                    $('#father_mobileno').val(result['father_mobileno']);
                                    $('#mother_fname').val(result['mother_fname']);
                                    $('#mother_lname').val(result['mother_lname']);
                                    $('#mother_mobileno').val(result['mother_mobileno']);                                    

                                }
			
                });
}
</script>




<script>


$(document).ready(function(){
    
    var text = $('#datatable-responsive_info').text();
    res = text.split("of");
    act_text = res[1].split("entries");
    $("<div id='custom_data_records'><label>Total Records : <span>" +act_text[0]+ "</span></label></div>").insertAfter('#datatable-responsive_length');
    
    $('input[type="search"]').keyup(function(){
        $('#custom_data_records').remove();
        var text = $('#datatable-responsive_info').text();
    res = text.split("of");
    act_text = res[1].split("entries");
    $("<div id='custom_data_records'><label>Total Records : <span>" +act_text[0]+ "</span></label></div>").insertAfter('#datatable-responsive_length');
    });
   
});



</script>


<script>
    
    <?php if($this->result['participant_Alumni']==1){ ?>
            $('.disabled input,.disabled select,.disabled textarea,.btn,button').attr('disabled','disabled');
        
    <?php } ?>
        $('#participant_pword').val('<?=$_SESSION['StuPword'];?>');
        
</script>

<script>
    
   var stu_id = $('#stu_id').val();
   $('#stu_id,#read_id').removeAttr('readonly');
  if(stu_id)
      $('#read_id').val(stu_id);
  
  $('#print').click(function(){
window.print('#grade_data');
});
  
    
    
    </script>
